version: "3.9"

services:
  db:
    container_name: gpa-db-dev
    image: postgres:14
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    env_file:
      - .env.desarrollo
    ports:
      - 5432:5432
  app:
    container_name: gpa-dev
    build:
      context: .
      dockerfile: Dockerfile.desarrollo
    command: tail -f /dev/null
    env_file:
      - .env.desarrollo
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
