FROM ubuntu:22.04
ENV PYTHONBUFFERED=1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes apt-get install -yq pip
RUN mkdir -p /django
WORKDIR /django
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt 2>/dev/null

COPY ./requirements-dev.txt requirements-dev.txt
RUN pip install -r requirements-dev.txt 2>/dev/null
