version: "3.9"

services:
  app:
    container_name: gpa-pro
    build:
      context: .
      dockerfile: Dockerfile.produccion
    command: gunicorn gestion_proyectos_agile.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.produccion
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static_volume:/app/staticfiles
volumes:
  static_volume:
