version: "3.3"

services:
  db:
    container_name: gpa-db-dev
    image: postgres:14
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
    env_file:
      - .env.desarrollo
    ports:
      - 5432:5432
  app:
    container_name: gpa-dev
    build:
      context: .
      dockerfile: Dockerfile.desarrollo
    command: bash -c "sleep 5 && python3 manage.py makemigrations usuarios proyectos historias_usuario && python3 manage.py migrate && python3 manage.py loaddata databasedump.json && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.desarrollo
    volumes:
      - .:/app
    ports:
      - "80:8000"
      - "8081:8081"
    depends_on:
      - db
